const { GoogleSpreadsheet } = require('google-spreadsheet');
const date = require('./date');


module.exports = async function saveData(data) {
    try {
        const doc = new GoogleSpreadsheet(
            '1eZ9z6ftuAxkD9l137CSmVwuWtzcETy4O1k4vkFKp5Ns'
        );
    
         doc.useServiceAccountAuth({
            // env var values are copied from service account credentials generated by google
            // see "Authentication" section in docs for more info
            client_email: process.env.EMAIL,
            private_key: process.env.KEY
        });
          
        await doc.loadInfo();
            
        await doc.sheetsByIndex[0].addRow({ 'Фамилия': data.lastName, 'Имя': data.firstName, 'Дата рождения': data.date, 'Город': data.city, 'Уровень английского': data.englishLevel, 'Опыт работы': data.previousExp, 'Telegram имя': data.tgName, 'Telegram username': data.username, 'Мобильный номер': data.phone, 'Дата заполнения': date()});
    
    } catch(e) {
        console.error('Ошибка отправки данных в таблицу');
    }
 }